parser: '@typescript-eslint/parser'
env:
  jest/globals: true

settings:
  import/resolver:
    node:
      extensions: [.js, .ts]

plugins:
  - '@typescript-eslint'
  - jest
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - prettier
