name: Setup Graphviz
description: Setup a graphviz environment and add it to the PATH.
author: kamiazya <yuki@kamiazya.tech>
branding:
  icon: arrow-down-circle
  color: gray-dark
inputs:
  ubuntu-graphviz-version:
    description: |-
      graphviz version on Ubuntu.
    required: false
  ubuntu-libgraphvizdev-version:
    description: |-
      libgraphviz-dev version on Ubuntu.
    required: false
  windows-graphviz-version:
    description: |-
      graphviz version on Windows.
    required: false

runs:
  using: node16
  main: lib/main.js
